# Site settings
title: jambla's Blog
email: qwe3243002@126.com
description: "FFF团员"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qwe3243002.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  qwe3243002
encoding: UTF-8

# Build settings
markdown: maruku
markdown_ext: markdown,mkd,mkdn,md